version: "3"
services:
  # ------------------------------------------
  db:
    build: ./db #for install extensions
    restart: always
    ports:
      - "${db_port}:5432"
    environment:
      # env vars specific to postgres image used on first boot
      - POSTGRES_USER=${db_postgres_user}
      - POSTGRES_PASSWORD=${db_postgres_password}
      - POSTGRES_DB=${db_name}
      # env vars useful for our sql scripts
      - APP_DB_LOGIN_USER=${db_login_user}
      - APP_DB_LOGIN_PASSWORD=${db_login_password}
      - APP_DB_SCHEMA=${db_schema}
      - APP_IS_DEVELOPMENT=${is_development}
      - APP_JWT_SECRET=${jwt_secret}
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - ~/postgres/data:/var/lib/postgresql/data
      - ~/postgres/log:/var/log/postgresql

  rest:
    image: postgrest/postgrest
    ports:
      - "3000"
    links:
      - postgres:db_host
    environment:
      - PGRST_DB_URI=postgres://${db_login_user}:${db_login_password}@db_host:5432/${db_name}
      - PGRST_DB_SCHEMA=${db_schema}
      - PGRST_DB_ANON_ROLE=${db_anon_role}
      - PGRST_DB_POOL=${db_pool}
      - PGRST_SERVER_PORT=3000
      - PGRST_SERVER_PROXY_URI=${server_proxy_uri}
      - PGRST_JWT_SECRET=${jwt_secret}
      - PGRST_MAX_ROWS=100
      - PGRST_PRE_REQUEST=${pre_request}
    depends_on:
      - postgres
  # ------------------------------------------

  nginx-react:
    build: ./nginx-react
    links:
      - rest:rest_host
      - node:node_host
    volumes:
      - ./nginx-react/react-app/build:/usr/share/nginx/html/app
      - ./nginx-react/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - ${app_port}:80
      - 443:443

  node:
    build: ./node
    links:
      - rest:rest_host
    ports:
      - ${app_node_port}:8081
