name: groups

table: |-
  (
    id                   serial primary key,
  	created_at					 timestamptz not null default now(),
  	updated_at					 timestamptz not null default now(),

  	name                 text not null,
  	user_id              int references data.users(id) not null default request.user_id()
  )

index:
  - user_id

rls:
  - public.rls_select('groups')
  - app_user.rls_insert('groups')
  - app_user.rls_update('groups', 'user_id = request.user_id()')
  - app_user.rls_delete('groups', 'user_id = request.user_id()')
  - app_admin.rls_delete('groups', 'true')

view:
  - name: groups
    define: |-
      create or replace view api.groups as
        select * from data.groups order by id desc
    rest:
      - public.rest_get('groups')
      - app_user.rest_post('groups', '(name)')
      - app_user.rest_patch('groups', '(name)')
      - app_user.rest_delete('groups')
      - app_admin.rest_delete('groups')

notify:
  - id

trigger:
  update: trigger_update_update_at()
