name: addresses

table: |-
  (
    id                   serial primary key,
  	created_at					 timestamptz not null default now(),
    updated_at					 timestamptz not null default now(),

    user_id              int references data.users(id) not null,

    country              text,
    state                text,
    city                 text,
    address1             text,
    address2             text,
    code                 text
  )

index:
  - user_id

rls:
  - app_user.rls_select('addresses', 'user_id = request.user_id()')
  - app_user.rls_insert('addresses')

view:
  - name: addresses
    define: |-
      create or replace view api.addresses as
        select * from data.addresses order by id desc
    rest:
      - app_user.rest_get('addresses')
      - app_user.rest_post('addresses', '(country, state, city, address1, address2, code)')

trigger:
  update: trigger_update_update_at()
